# Build Pipeline - Pull Request

trigger: none

pr:
- main
- development

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'

steps:
- task: NuGetToolInstaller@1
  displayName: Install NuGet Tool

- task: NuGetCommand@2
  displayName: Restore Solution
  inputs:
    restoreSolution: '$(solution)'

- task: SonarQubePrepare@5
  displayName: Prepare Analysis Configuration
  inputs:
    SonarQube: 'SonarQube'
    scannerMode: 'MSBuild'
    projectKey: 'Ethos-Integration-SDK'

- task: VSBuild@1
  displayName: Build Solution
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: SonarQubeAnalyze@5
  displayName: SonarQube - Run Code Analysis

- task: SonarQubePublish@5
  displayName: SonarQube - Publish Quality Gate Result
  inputs:
    pollingTimeoutSec: '300'

- task: sonar-buildbreaker@8
  inputs:
    SonarQube: 'SonarQube'
